# Generated by Django 6.0.4 on 2026-04-13 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Bo'lim nomi")),
                ('description', models.TextField(blank=True, verbose_name="Bo'lim haqida")),
                ('image', models.ImageField(blank=True, upload_to='departments/', verbose_name='Rasm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('name', models.CharField(max_length=255, verbose_name='Tahlil nomi')),
                ('price', models.FloatField(verbose_name='Narxi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
            ],
            options={
                'verbose_name': 'Laboratoriya tahlili',
                'verbose_name_plural': 'Laboratoriya tahlillari',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Maqola')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Rasm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('full_name', models.CharField(max_length=200, verbose_name='Bemor F.I.Sh')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqami')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sanasi")),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzili')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
            ],
            options={
                'verbose_name': 'Bemor',
                'verbose_name_plural': 'Bemorlar',
            },
        ),
        migrations.CreateModel(
            name='LabReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Tayyor')], default='pending', max_length=20, verbose_name='Holati')),
                ('result_text', models.TextField(blank=True, verbose_name='Natija')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.labtest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_referrals', to='mainApp.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('date', models.DateField(verbose_name='Sana')),
                ('time_slot', models.TimeField(verbose_name='Vaqt')),
                ('status', models.CharField(choices=[('waiting', 'Kutilmoqda'), ('received', 'Qabul qilindi'), ('paid', 'Toʻlov qilindi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='waiting', max_length=20, verbose_name='Holati')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='mainApp.patient')),
            ],
            options={
                'verbose_name': 'Klinika Navbati',
                'verbose_name_plural': 'Klinika Navbatlari',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('amount', models.FloatField(verbose_name='Summa')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta')], default='cash', max_length=10, verbose_name='Turi')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='mainApp.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('name', models.CharField(max_length=200, verbose_name='Xizmat nomi')),
                ('price', models.FloatField(verbose_name='Narxi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='mainApp.department')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.service'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('role', models.CharField(choices=[('doctor', 'Shifokor'), ('reception', 'Reseption'), ('admin', 'Admin')], max_length=20, verbose_name='Lavozimi')),
                ('full_name', models.CharField(max_length=200, verbose_name='F.I.Sh')),
                ('photo', models.ImageField(default='default-staff.png', upload_to='staff/', verbose_name='Rasm')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='Tashxis')),
                ('prescription', models.TextField(verbose_name='Retsept')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='mainApp.patient')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.staff')),
            ],
            options={
                'verbose_name': 'Tibbiy karta',
                'verbose_name_plural': 'Tibbiy kartalar',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('specialization', models.CharField(max_length=255, verbose_name='Mutaxassisligi')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Ish staji (yil)')),
                ('slot_duration', models.IntegerField(default=30, verbose_name='Bemorga vaqt (min)')),
                ('bio', models.TextField(blank=True, verbose_name='Shifokor haqida')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
                ('staff', models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_details', to='mainApp.staff')),
            ],
            options={
                'verbose_name': 'Shifokor profili',
                'verbose_name_plural': 'Shifokorlar profillari',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to='mainApp.staff'),
        ),
        migrations.CreateModel(
            name='OnlineAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('patient_name', models.CharField(max_length=200, verbose_name='Bemor ismi')),
                ('patient_phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('date', models.DateField(verbose_name='Sana')),
                ('time_slot', models.TimeField(verbose_name='Vaqt')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.service')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to='mainApp.staff')),
            ],
            options={
                'verbose_name': 'Online Navbat',
                'verbose_name_plural': 'Online Navbatlar',
                'unique_together': {('doctor', 'date', 'time_slot')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'time_slot')},
        ),
    ]
