# Generated by Django 6.0.4 on 2026-04-13 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labreferral',
            options={'verbose_name': "Laboratoriya yo'llanmasi", 'verbose_name_plural': "Laboratoriya yo'llanmalari"},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name="To'langanlik holati"),
        ),
        migrations.AddField(
            model_name='payment',
            name='online_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='mainApp.onlineappointment', verbose_name='Online navbat'),
        ),
        migrations.AlterField(
            model_name='labreferral',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_referrals', to='mainApp.patient', verbose_name='Bemor'),
        ),
        migrations.AlterField(
            model_name='labreferral',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.labtest', verbose_name='Tahlil turi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Maqola mazmuni'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(verbose_name="To'lov summasi"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='mainApp.appointment', verbose_name='Klinika navbati'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('online', 'Online')], default='cash', max_length=10, verbose_name="To'lov turi"),
        ),
    ]
