# Generated by Django 6.0.4 on 2026-04-14 01:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_service_description_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
    ]
