# Generated by Django 6.0.4 on 2026-04-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ismi')),
                ('email', models.EmailField(max_length=254, verbose_name='Email manzili')),
                ('subject', models.CharField(max_length=255, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qildimi?")),
            ],
            options={
                'verbose_name': "Bog'lanish xabari",
                'verbose_name_plural': "Bog'lanish xabarlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
