# Generated by Django 6.0.4 on 2026-04-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_staff_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('graduated_year', models.CharField(max_length=50, verbose_name='Bitirgan yil')),
                ('specialization', models.CharField(max_length=255, verbose_name='Mutaxassislik')),
                ('university', models.CharField(max_length=255, verbose_name='Universitet')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='mainApp.staff')),
            ],
            options={
                'verbose_name': 'Xodim tahsili',
                'verbose_name_plural': 'Xodimlar tahsili',
            },
        ),
        migrations.CreateModel(
            name='StaffExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('years', models.CharField(max_length=100, verbose_name='Yillar')),
                ('department', models.CharField(max_length=255, verbose_name="Bo'lim")),
                ('position', models.CharField(max_length=255, verbose_name='Lavozim')),
                ('hospital', models.CharField(max_length=255, verbose_name='Shifoxona')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='mainApp.staff')),
            ],
            options={
                'verbose_name': 'Xodim ish tajribasi',
                'verbose_name_plural': 'Xodimlar ish tajribalari',
            },
        ),
        migrations.CreateModel(
            name='StaffSocialContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_contacts', to='mainApp.staff')),
            ],
            options={
                'verbose_name': "Xodim aloqa ma'lumoti",
                'verbose_name_plural': "Xodimlar aloqa ma'lumotlari",
            },
        ),
    ]
