# Generated by Django 6.0.4 on 2026-04-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_staffeducation_staffexperience_staffsocialcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineappointment',
            name='service',
        ),
    ]
