# Generated by Django 6.0.4 on 2026-04-16 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_remove_onlineappointment_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AddField(
            model_name='appointment',
            name='lab_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.labtest', verbose_name='Laboratoriya tahlili'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.service', verbose_name='Tibbiy xizmat'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name="To'lov summasi"),
        ),
    ]
