# Generated by Django 6.0.4 on 2026-04-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_appointment_options_appointment_lab_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_consultation',
            field=models.BooleanField(default=False, verbose_name="Shunchaki shifokor ko'rigi (Konsultatsiya)"),
        ),
    ]
