# Generated by Django 6.0.4 on 2026-04-16 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_appointment_is_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_consultation',
            field=models.BooleanField(default=False, verbose_name="Shifokor ko'rigi"),
        ),
        migrations.AddField(
            model_name='payment',
            name='lab_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.labtest', verbose_name='Laboratoriya tahlili'),
        ),
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.service', verbose_name='Tibbiy xizmat'),
        ),
    ]
