# Generated by Django 6.0.4 on 2026-04-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_payment_is_consultation_payment_lab_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
    ]
