# Generated by Django 6.0.4 on 2026-04-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_remove_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(default='Nomalum', max_length=255, verbose_name='Bemorning ism-familiyasi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(default='+998 88 7675465', max_length=20, verbose_name='Telefon raqami'),
            preserve_default=False,
        ),
    ]
