# Generated by Django 6.0.4 on 2026-04-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_appointment_patient_name_appointment_patient_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(default='default', help_text="Asosiy sahifada ko'rinadigan qisqa matn", max_length=500, verbose_name='Qisqa mazmun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
    ]
