# Generated by Django 6.0.4 on 2026-04-17 16:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_alter_news_options_news_slug_news_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Maqola mazmuni'),
        ),
    ]
