# Generated by Django 6.0.4 on 2026-04-17 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineappointment',
            name='department',
            field=models.ForeignKey(default='16', on_delete=django.db.models.deletion.CASCADE, to='mainApp.department', verbose_name="Bo'lim"),
            preserve_default=False,
        ),
    ]
