# Generated by Django 6.0.4 on 2026-04-17 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_onlineappointment_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='mainApp.department', verbose_name="Bo'lim"),
            preserve_default=False,
        ),
    ]
