# Generated by Django 6.0.4 on 2026-04-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_appointment_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineappointment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot yoki shikoyat"),
        ),
    ]
