# Generated by Django 6.0.4 on 2026-05-02 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mainApp', '0018_onlineappointment_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Yaratildi'), ('update', 'Tahrirlandi'), ('delete', "O'chirildi")], max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(max_length=255, verbose_name="O'zgartirilgan obyekt nomi")),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul xodim")),
            ],
            options={
                'verbose_name': 'Harakatlar jurnali',
                'verbose_name_plural': 'Harakatlar jurnali',
                'ordering': ['-timestamp'],
            },
        ),
    ]
