# Generated by Django 6.0.4 on 2026-05-02 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mainApp', '0019_actionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Harakat', 'verbose_name_plural': 'Harakatlar jurnali'},
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('create', 'Yaratildi'), ('update', 'Tahrirlandi'), ('delete', "O'chirildi")], max_length=10, verbose_name='Harakat'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name="Bo'lim"),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='object_repr',
            field=models.CharField(max_length=255, verbose_name="O'zgartirilgan obyekt"),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vaqt'),
        ),
    ]
