# Generated by Django 6.0.4 on 2026-05-02 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_alter_actionlog_options_alter_actionlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='mainApp.appointment', verbose_name='Klinika navbati'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='online_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='mainApp.onlineappointment', verbose_name='Online navbat'),
        ),
    ]
